version: '3'

services:
  tsundoku:
    build:
      context: ../server/
      dockerfile: ../development/Dockerfile
    env_file:
      - .env
    volumes:
      - ../server:/tsundoku/server
      # For exclude node_modules
      - node_modules:/tsundoku/server/ogp_canvas/node_modules
      # - ../ogp_canvas/screenshots:/tsundoku/ogp/screenshots
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: tsundoku
    ports:
      - "3306:3306"
volumes:
  node_modules:
    driver: "local"
  # ogp:
  #   build:
  #     context: ../ogp/
  #     dockerfile: ../development/ogp.Dockerfile
  #   volumes:
  #     - ../ogp/screenshots:/tsundoku/ogp/screenshots
