version: '3'

services:
  tsundoku:
    build:
      context: ../server/
      dockerfile: ../development/Dockerfile
    env_file:
      - .env
    volumes:
      - ../server:/tsundoku/server
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: tsundoku
    ports:
      - "3306:3306"
  ogp:
    build:
      context: ../ogp
      dockerfile: ../development/ogp.Dockerfile
    ports:
      - "3001:3001"
