# Build Frontend Static Files
FROM node:14.4.0 as build
WORKDIR /app
COPY client/package*.json ./
RUN npm install
COPY client .
RUN NODE_ENV=production npm run build
# ----------------------------------------------------------------------------------- //

FROM caddy:2.1.1-alpine
EXPOSE 80 443
COPY Caddyfile /etc/caddy/Caddyfile
COPY --from=build /app/dist /usr/share/caddy
# ----------------------------------------------------------------------------------- //
