version: "3"

services:
  tsundoku:
    build:
      context: .
      image: unipota/tsudoku/tsundoku-app:latest
    environment:
      VIRTUAL_HOST: tsun-doku.app
      LETSENCRYPT_HOST: tsun-doku.app
      LETSENCRYPT_EMAIL: woz.eon@gmail.com
    volumes:
      - ./server/ogp_canvas/screenshots:/tsundoku/server/ogp_canvas/screenshots:rw
      # - ./ogp/screenshots:/tsundoku/ogp/screenshots:rw
    env_file:
      - .env
    expose:
      - 3000
    depends_on:
      - nginx-proxy
      - db
    restart: always
  nginx-proxy:
    image: jwilder/nginx-proxy
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=jwilder/nginx-proxy
    privileged: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker-compose.d/certs:/etc/nginx/certs:ro
      - ./docker-compose.d/htpasswd:/etc/nginx/htpasswd
      - proxy:/etc/nginx/vhost.d
      - proxy:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  letsencrypt-nginx:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx
    privileged: true
    volumes:
      - proxy:/etc/nginx/vhost.d
      - proxy:/usr/share/nginx/html
      - ./docker-compose.d/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    depends_on:
      - nginx-proxy
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: tsundoku
    volumes:
      - ./db/mysql_data:/var/lib/mysql

volumes:
  proxy:
