version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    env_file:
      - .env
    command: ./app
    expose:
      - "3000"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 50M

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: always
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 50M

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: tsundoku
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    expose:
      - "3306"
    deploy:
      resources:
        limits:
          memory: 300M
