version: "3.7"

services:
  backend:
    image: ghcr.io/unipota/tsundoku:latest
    restart: always
    env_file:
      - .env
    expose:
      - "3000"
    depends_on:
      - db
    networks:
      - default
      - caddy
    labels:
      caddy: api.tsun-doku.app
      caddy.reverse_proxy: "{{upstreams 3000}}"

  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: tsundoku
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    expose:
      - "3306"
    networks:
      - default

networks:
  caddy:
    external: true

volumes:
  caddy_data: {}