version: "3.8"

services:
  backend:
    image: docker.pkg.github.com/unipota/tsundoku/tsundoku-backend:latest
    restart: always
    env_file:
      - .env
    command: ./app
    expose:
      - "3000"
    depends_on:
      - db

  frontend:
    image: docker.pkg.github.com/unipota/tsundoku/tsundoku-frontend:latest
    restart: always
    expose:
      - "80"
      - "443"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data:/data
      - ./certs:/root/certs
    depends_on:
      - backend

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: tsundoku
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    expose:
      - "3306"
