name: deploy

on:
  push:
    branches:
      - master

env:
  BACKEND_IMAGE_NAME: tsundoku-backend
  BACKEND_DOCKERFILE: Dockerfile.backend
  FRONTEND_IMAGE_NAME: tsundoku-frontend
  FRONTEND_DOCKERFILE: Dockerfile.frontend

jobs:
  backend-image:
    name: Build Backend Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login GitHub Registry
        run: docker login docker.pkg.github.com -u unipota -p ${{ secrets.GITHUB_TOKEN }}
      - name: Build Image
        run: docker build -t docker.pkg.github.com/unipota/tsundoku/${BACKEND_IMAGE_NAME} -f ${BACKEND_DOCKERFILE}
      - name: Push image to GitHub Registry
        run: docker push docker.pkg.github.com/unipota/tsundoku/${BACKEND_IMAGE_NAME}
      - name: Push image to GitHub Registry (latest)
        run: |
          docker tag docker.pkg.github.com/unipota/tsundoku/${BACKEND_IMAGE_NAME} docker.pkg.github.com/unipota/tsundoku/${BACKEND_IMAGE_NAME}:latest
          docker push docker.pkg.github.com/unipota/tsundoku/${BACKEND_IMAGE_NAME}:latest

  frontend-image:
    name: Build Frontend Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login GitHub Registry
        run: docker login docker.pkg.github.com -u unipota -p ${{ secrets.GITHUB_TOKEN }}
      - name: Build Image
        run: docker build -t docker.pkg.github.com/unipota/tsundoku/${FRONTEND_IMAGE_NAME} -f ${FRONTEND_DOCKERFILE}
      - name: Push image to GitHub Registry
        run: docker push docker.pkg.github.com/unipota/tsundoku/${FRONTEND_IMAGE_NAME}
      - name: Push image to GitHub Registry (latest)
        run: |
          docker tag docker.pkg.github.com/unipota/tsundoku/${FRONTEND_IMAGE_NAME} docker.pkg.github.com/unipota/tsundoku/${FRONTEND_IMAGE_NAME}:latest
          docker push docker.pkg.github.com/unipota/tsundoku/${FRONTEND_IMAGE_NAME}:latest
